export const API_URL = 'http://apis.eeme.io/api'

export const STORAGE_LINK = 'https://storage.googleapis.com/omneeyat_gcs'

const ABOUT_PAGE_ID = 1;
const TERMS_PAGE_ID = 2;
const PRIVACY_PAGE_ID = 3;
const CONTACT_PAGE_ID = 4;
const HOME_PAGE_ID = 5;
const SINGLE_PAGE_ID = 6;
const ARTICLE_PAGE_ID = 7;
const BOOK_PAGE_ID = 8;
const DONATE_PAGE_ID = 9;
const VIDEO_PAGE_ID = 14;
const TALENT_TEMP_PAGE_ID = 15;
const TALENT_PAGE_ID = 15;
const FILMOGRAPHY_PAGE_ID = 16;
const PENDING_PAGE_ID = 17;
const CANCELLED_PAGE_ID = 18;
const DECLINED_PAGE_ID = 19;
const SUCCESS_PAGE_ID = 20;
const NEWS_PAGE_ID = 33;
const ONBOARDING_ID = 42;
const TALENT_INDEX_PAGE_ID = 76;
const CATEGORY_INDEX_PAGE = 77;


const INSTAGRAM_SOCIAL_MEDIA_ID = 3;
const YOUTUBE_SOCIAL_MEDIA_ID = 6;
const TIKTOK_SOCIAL_MEDIA_ID = 5;
const YOUTUBE_PLATFORM_EMBED_ID = 2;
const YOUTUBE_PLATFORM_ID = 5;

const VIDEO_ORDER_TYPE = 1;
const BUSINESS_ORDER_TYPE = 2;
const CAMPAIGN_ORDER_TYPE = 3;

const IN_THE_SPOT = 1;
const IN_THE_MEDIA = 2;
const FILMOGRAPHY = 3;
const TALENT_SOCIAL = 4;
const TALENT_VIDEOS = 5;
const INSIGHTS = 6 ;
const COLLABS = 7 ;

const CANCELLED_PAYMENT = -2;
const SUCCESS_PAYMENT = 3;
const PENDING_PAYMENT = 1;


const EXTRA_SETTINGS = [
    {1: { en: 'Creators are required to confirm their delivery address when accepting', ar: 'مطلوب من المنشئين تأكيد عنوان التسليم الخاص بهم لدى قبول دفعات متعددة' },},
    {2: { en: 'Multiple payments', ar: 'مدفوعات متعددة' }},
];

const PAYMENT_METHODS: { [key: number]: string } = {
    0: 'Western Union',
    1: 'Credit Card',
    2: 'PayPal',
    3: 'Free',
    4: 'Via WhatsApp'
};


export {PENDING_PAYMENT , PAYMENT_METHODS , CANCELLED_PAYMENT , SUCCESS_PAYMENT, EXTRA_SETTINGS , VIDEO_ORDER_TYPE , BUSINESS_ORDER_TYPE , CAMPAIGN_ORDER_TYPE, IN_THE_MEDIA, IN_THE_SPOT, FILMOGRAPHY , TALENT_SOCIAL , INSIGHTS , COLLABS , TALENT_VIDEOS , YOUTUBE_PLATFORM_EMBED_ID , YOUTUBE_PLATFORM_ID , INSTAGRAM_SOCIAL_MEDIA_ID , YOUTUBE_SOCIAL_MEDIA_ID, TIKTOK_SOCIAL_MEDIA_ID ,ABOUT_PAGE_ID , TERMS_PAGE_ID, PRIVACY_PAGE_ID,CANCELLED_PAGE_ID,CONTACT_PAGE_ID,ARTICLE_PAGE_ID,DECLINED_PAGE_ID,SUCCESS_PAGE_ID,VIDEO_PAGE_ID,HOME_PAGE_ID,FILMOGRAPHY_PAGE_ID,BOOK_PAGE_ID,ONBOARDING_ID,SINGLE_PAGE_ID,NEWS_PAGE_ID,DONATE_PAGE_ID,TALENT_TEMP_PAGE_ID,TALENT_INDEX_PAGE_ID,PENDING_PAGE_ID , CATEGORY_INDEX_PAGE,TALENT_PAGE_ID}